# Accident Severity Predictor (ASP) - docker-compose.yaml
#
# Usage:
#   docker compose up -d --build backend
#   docker compose down

services:
  backend:
    build:
      context: .
      dockerfile: services/backend/Dockerfile.backend
      args:
        USER_ID: ${UID:-1000}
        GROUP_ID: ${GID:-1000}
        # solve: ERROR - stderr: permission denied
        # while trying to connect to the docker API at unix:///var/run/docker.sock
        # DOCKER_GID: ${DOCKER_GID}
    image: asp-backend:latest
    container_name: asp-backend
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data
      - ./artifacts:/app/artifacts
      - /var/run/docker.sock:/var/run/docker.sock

    # save abs path in an .env file
    environment:
      HOST_DATA_DIR: ${HOST_PROJECT_ROOT}/data
      HOST_ARTIFACTS_DIR: ${HOST_PROJECT_ROOT}/artifacts
      DAGSHUB_USER_TOKEN: ${DAGSHUB_USER_TOKEN}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/v1/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    restart: unless-stopped
    networks:
      - asp-network

  # training service only for building an image
  training:
    build:
      context: .
      dockerfile: services/training/Dockerfile.training
      args:
        USER_ID: ${UID}
        GROUP_ID: ${GID}
    image: asp-training:latest
    profiles: ["build-only"]  # add profile so it not starts with docker compose up
    # only to comfirm build is done
    command: ["echo", "Training image built"]
    networks:
      - asp-network

  frontend:
    build:
      context: .
      dockerfile: services/frontend/Dockerfile.frontend
    image: asp-frontend:latest
    container_name: asp-frontend
    ports:
      - "8501:8501"
    depends_on:
      backend:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - asp-network

networks:
  asp-network:
    name: asp-network
    driver: bridge
