name: ASP CI

on:
  push:
    branches:
      - main
      - develop

  pull_request:
    branches:
      - main
      - develop

jobs:
  lint:
    uses: ./.github/workflows/asp-lint.yaml

  tests:
    needs: lint
    uses: ./.github/workflows/asp-tests.yaml
  
  docker:
    needs: tests
    uses: ./.github/workflows/asp-docker.yaml
